<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Скидочная система");
?><? $APPLICATION->IncludeComponent("bitrix:news.detail", "certificate", Array(
		"ACTIVE_DATE_FORMAT"        => "d.m.Y",
		"ADD_ELEMENT_CHAIN"         => "N",
		"ADD_SECTIONS_CHAIN"        => "N",
		"AJAX_MODE"                 => "N",
		"AJAX_OPTION_ADDITIONAL"    => "",
		"AJAX_OPTION_HISTORY"       => "N",
		"AJAX_OPTION_JUMP"          => "N",
		"AJAX_OPTION_STYLE"         => "N",
		"BROWSER_TITLE"             => "-",
		"CACHE_GROUPS"              => "N",
		"CACHE_TIME"                => "36000000",
		"CACHE_TYPE"                => "A",
		"CHECK_DATES"               => "Y",
		"DETAIL_URL"                => "",
		"DISPLAY_BOTTOM_PAGER"      => "N",
		"DISPLAY_DATE"              => "N",
		"DISPLAY_NAME"              => "Y",
		"DISPLAY_PICTURE"           => "Y",
		"DISPLAY_PREVIEW_TEXT"      => "N",
		"DISPLAY_TOP_PAGER"         => "N",
		"ELEMENT_CODE"              => "skidochnaya-sistema",
		"ELEMENT_ID"                => "",
		"FIELD_CODE"                => array("", ""),
		"IBLOCK_ID"                 => "29",
		"IBLOCK_TYPE"               => "onas",
		"IBLOCK_URL"                => "",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"MESSAGE_404"               => "",
		"META_DESCRIPTION"          => "-",
		"META_KEYWORDS"             => "-",
		"PAGER_BASE_LINK_ENABLE"    => "N",
		"PAGER_SHOW_ALL"            => "N",
		"PAGER_TEMPLATE"            => ".default",
		"PAGER_TITLE"               => "Страница",
		"PROPERTY_CODE"             => array("TEXT_AFTER_PIC", "TEXT_BEFORE_PIC"),
		"SET_BROWSER_TITLE"         => "Y",
		"SET_CANONICAL_URL"         => "N",
		"SET_LAST_MODIFIED"         => "N",
		"SET_META_DESCRIPTION"      => "Y",
		"SET_META_KEYWORDS"         => "Y",
		"SET_STATUS_404"            => "Y",
		"SET_TITLE"                 => "Y",
		"SHOW_404"                  => "N",
		"STRICT_SECTION_CHECK"      => "N",
		"USE_PERMISSIONS"           => "N",
		"USE_SHARE"                 => "N"
	)); ?>
<? require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php"); ?>